# Generated by Django 2.2.2 on 2019-10-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mascot', models.CharField(max_length=40)),
                ('abbreviation', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Conference')),
            ],
        ),
    ]
