# Generated by Django 2.2.2 on 2019-10-18 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='conference',
            field=models.ForeignKey(default='Independent', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Conference'),
        ),
    ]
