# Generated by Django 2.2.2 on 2019-10-18 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191017_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Conference'),
        ),
    ]
