# Generated by Django 2.2.2 on 2019-10-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191017_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
