# Generated by Django 2.2.2 on 2019-10-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.Coach'),
        ),
    ]
