# Generated by Django 2.2.2 on 2019-10-29 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='ai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.AI'),
        ),
    ]
