# Generated by Django 2.2.2 on 2019-10-29 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_coach_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.AI'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
