# Generated by Django 2.2.2 on 2019-11-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191029_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.School'),
        ),
    ]
