# Generated by Django 2.2.2 on 2019-11-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
