# Generated by Django 2.2.2 on 2019-11-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_game_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='awayScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homeScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
