# Generated by Django 2.2.2 on 2019-11-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191103_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
