# Generated by Django 2.2.2 on 2019-11-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.School'),
        ),
    ]
