# Generated by Django 2.2.2 on 2020-01-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20191115_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.Coach'),
        ),
    ]
