# Generated by Django 2.2.2 on 2020-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200106_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='abbreviation',
            field=models.CharField(max_length=4),
        ),
    ]
