# Generated by Django 2.2.2 on 2020-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200114_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='division1',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='division2',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
