# Generated by Django 2.2.2 on 2020-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200430_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='division1',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
