# Generated by Django 2.2.2 on 2020-05-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200503_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('DT', 'Defensive Tackle'), ('EDGE', 'Edge Defender'), ('LB', 'Linebacker'), ('CB', 'Cornerback'), ('S', 'Safety'), ('K', 'Kicker'), ('P', 'Punter')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
