# Generated by Django 2.2.2 on 2020-05-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='t_arm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='t_athleticism',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='t_dexterity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='t_iq',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='t_leg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='t_personality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='t_strength',
            field=models.FloatField(default=0.0),
        ),
    ]
