# Generated by Django 2.2.2 on 2020-05-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200503_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='s_armAccLong',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_armAccMed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_armAccShort',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_armStr',
            field=models.FloatField(default=0.0),
        ),
    ]
