# Generated by Django 2.2.2 on 2020-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200504_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stars',
            field=models.IntegerField(default=2),
        ),
    ]
