# Generated by Django 2.2.2 on 2020-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_player_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='s_acceleration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_agility',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_coverMan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_coverZone',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_hands',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_kickAcc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_kickPow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_passBlock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_puntAcc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_puntPow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_readDefPass',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_readDefRun',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_readOff',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_runBlock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_runPower',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_shedBlockAgl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_shedBlockStr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_tackApproach',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_tackBringDown',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='s_vertical',
            field=models.FloatField(default=0.0),
        ),
    ]
