# Generated by Django 2.2.2 on 2020-05-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_player_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteam',
            name='age',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('AL', 'Alum')], default='FR', max_length=2),
            preserve_default=False,
        ),
    ]
