# Generated by Django 2.2.2 on 2020-05-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_playerteam_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteam',
            name='string',
            field=models.IntegerField(default=99),
        ),
    ]
