# Generated by Django 2.2.2 on 2020-05-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_playerteam_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'Future'), ('P', 'In Progress'), ('C', 'Complete')], default='F', max_length=1),
        ),
    ]
