# Generated by Django 2.2.2 on 2020-05-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isScrimmage',
            field=models.BooleanField(default=False),
        ),
    ]
