# Generated by Django 2.2.2 on 2020-06-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200606_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='plays',
            field=models.CharField(blank=True, max_length=999999, null=True),
        ),
    ]
