# Generated by Django 2.2.2 on 2020-06-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20200613_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefensiveFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isBase', models.BooleanField()),
                ('linemen', models.IntegerField(default=0)),
                ('linebackers', models.IntegerField(default=0)),
                ('corners', models.IntegerField(default=0)),
                ('safeties', models.IntegerField(default=0)),
            ],
        ),
    ]
